# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
port: 4000
host: 0.0.0.0
locale: "ja-JP"  # 日本語
title: mofmofinc
email: info@mof-mof.co.jp
name: 月額制受託開発の株式会社mofmof
description: > # this means to ignore newlines until "baseurl:"
  システム開発会社ならアジャイル月額制受託のmofmofへ。高速に最小限のアプリやWebサービス等を制作し、実際に動かして検証しながら開発を繰り返し「本当に欲しかったもの」を実現します。新規IT事業にともなう開発案件の相談にも乗ります。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
permalink: none
# destination: docs
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
